# Bad login
POST http://localhost:3001/api/sessions
content-type: application/json

{
    "username": "mario.rossi",
    "password": "wrong_password"
}

###

# Good login
POST http://localhost:3001/api/sessions
content-type: application/json

{
    "username": "mario.rossi",
    "password": "password_di_mario"
}

###

# Logout
DELETE http://localhost:3001/api/sessions/current

###

# Rebuild session
GET http://localhost:3001/api/sessions/current

###

# List Players
GET http://localhost:3001/api/players

###

# List Stations
GET http://localhost:3001/api/stations

###

# List Segments
GET http://localhost:3001/api/segments

###

# List Lines
GET http://localhost:3001/api/lines

###

# List Events
GET http://localhost:3001/api/events

###

# Update score
PATCH http://localhost:3001/api/score
content-type: application/json

{
    "score": 19
}